### ISSUE TITLE
Is it possible to start a docker container and access your redis server ?

### ISSUE THREAD

**Issue by qiulang** [shogo82148/actions-setup-redis#508]
Hi I start my docker container after `uses: shogo82148/actions-setup-redis@v1` 
My container needs to access a redis-server, what host value should I use to access the redis server your action starts ?
Or is that possible ?

Thanks!

**Comment by shogo82148** [comment]
It is probably possible, but I do not know how.

I think it is better to start redis-server with docker too
https://docs.github.com/en/actions/using-containerized-services/creating-redis-service-containers

**Comment by qiulang** [comment]
Thanks for answering it.
