### ISSUE TITLE
What is the hostname?

### ISSUE THREAD

**Issue by SirPhemmiey** [shogo82148/actions-setup-redis#774]
Hey man, thanks for this action. 

I'd like to know what the hostname is. Is it localhost, 127.0.0.1 or redis-server? 

Looking forward to hearing from you. 

Thanks!

**Comment by shogo82148** [comment]
It is `127.0.0.1`. https://github.com/shogo82148/actions-setup-redis/blob/48c92d03ef0af357e32e6d671b79eba091077fc2/src/starter.ts#L49

**Comment by SirPhemmiey** [comment]
On the other hand, I'm getting this error

```

  Error: getaddrinfo EAI_AGAIN redis
  at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26) {
errno: -3001,
 code: 'EAI_AGAIN',
 syscall: 'getaddrinfo',
  hostname: 'redis'
```

do you know how to fix this, please?

**Comment by SirPhemmiey** [comment]
I'm replacing with `127.0.0.1` and trying again.

**Comment by SirPhemmiey** [comment]
that worked, thanks
