### ISSUE TITLE
Skip certificates generation if TLS is disabled

### ISSUE THREAD

**Issue by victormferrara** [shogo82148/actions-setup-redis#899]
Hi, thank you for this useful action!

I've realized that some times the certificates generation to support TLS can take a bit of time (almost a minute). Would it make sense to skip this part if TLS is not enabled? I'd say it would imply just checking the `tlsPort` value [here](https://github.com/shogo82148/actions-setup-redis/blob/0610079487a9527339ee82799070b7e94a83ad3a/src/starter.ts#L93). Tbh I'm not an expert here and I don't know if Redis versions that support TLS actually expect that setup even if it's not used.

Cheers!

**Comment by shogo82148** [comment]
Sounds good.
I'll implement it.
